import { Head, Link, useForm } from '@inertiajs/react';
import PasswordField from '@/components/password-field';
import AdminLayout from '@/layouts/admin-layout';

export default function AccountForm({ role }: { role: 'Petugas' | 'Pengguna' }) {
    const form = useForm({ nama: '', email: '', password: '', password_confirmation: '' });
    const endpoint = role === 'Petugas' ? '/admin/users/petugas' : '/admin/users/pengguna';
    const errors = Object.values(form.errors);
    return <AdminLayout><Head title={`Buat Akun ${role}`} /><div className="mx-auto max-w-2xl overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 p-6"><h1 className="text-xl font-bold">Buat Akun {role}</h1><p className="mt-1 text-xs text-slate-500">{role === 'Petugas' ? 'Akun Petugas dibuat langsung aktif dan dapat langsung masuk ke sistem.' : 'Akun Pengguna yang dibuat langsung oleh Admin langsung aktif.'}</p></div><div className="p-6">{errors.length > 0 && <div role="alert" className="mb-5 rounded border-l-4 border-rose-500 bg-rose-50 p-4 text-sm text-rose-800">{errors.map((error) => <div key={error}>{error}</div>)}</div>}<form onSubmit={(event) => { event.preventDefault(); form.post(endpoint); }} className="space-y-4"><div><label htmlFor="nama" className="mb-1 block text-sm font-medium text-slate-700">Nama Lengkap {role}</label><input id="nama" required autoFocus value={form.data.nama} onChange={(event) => form.setData('nama', event.target.value)} placeholder={role === 'Petugas' ? 'Contoh: Ahmad Fadilah' : 'Contoh: Siti Rahmawati'} className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm" /></div><div><label htmlFor="email" className="mb-1 block text-sm font-medium text-slate-700">Alamat Email {role === 'Petugas' ? 'Resmi' : 'Kampus'}</label><input id="email" type="email" required value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} placeholder="nama@kampus.ac.id" className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm" /></div><div className="grid gap-4 md:grid-cols-2"><PasswordField label="Kata Sandi" name="password" placeholder="Minimal 8 karakter" value={form.data.password} onChange={(value) => form.setData('password', value)} /><PasswordField label="Konfirmasi Kata Sandi" name="password_confirmation" placeholder="Ulangi kata sandi" value={form.data.password_confirmation} onChange={(value) => form.setData('password_confirmation', value)} /></div><div className="flex justify-end gap-3 pt-4"><Link href="/admin/users" className="px-4 py-2 text-xs text-slate-600">Batal</Link><button disabled={form.processing} className="rounded-md bg-[#2D4C79] px-5 py-2 text-sm font-medium text-white shadow-sm hover:bg-[#1e3454] disabled:opacity-60">Simpan Akun {role}</button></div></form></div></div></AdminLayout>;
}
