import { Head, Link, useForm } from '@inertiajs/react';
import PasswordField from '@/components/password-field';
import AdminLayout from '@/layouts/admin-layout';

export default function ChangePassword() {
    const form = useForm({ current_password: '', password: '', password_confirmation: '' });
    const errors = Object.values(form.errors);
    return <AdminLayout><Head title="Ganti Password Admin" /><div className="w-full overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 bg-slate-50 p-6"><h1 className="text-xl font-bold">Ganti Password Administrator (GAL-07 / BR-18)</h1><p className="mt-1 text-xs text-slate-500">Perbarui kata sandi akun Anda secara berkala untuk menjaga keamanan sistem.</p></div><div className="p-6">{errors.length > 0 && <div role="alert" className="mb-5 rounded border-l-4 border-rose-500 bg-rose-50 p-4 text-sm text-rose-800">{errors.map((error) => <div key={error}>{error}</div>)}</div>}<form onSubmit={(event) => { event.preventDefault(); form.put('/admin/change-password'); }} className="space-y-4"><PasswordField label="Kata Sandi Saat Ini" name="current_password" placeholder="Masukkan kata sandi saat ini" value={form.data.current_password} onChange={(value) => form.setData('current_password', value)} autoFocus /><PasswordField label="Kata Sandi Baru" name="password" placeholder="Minimal 8 karakter dan berbeda dari sebelumnya" value={form.data.password} onChange={(value) => form.setData('password', value)} /><PasswordField label="Konfirmasi Kata Sandi Baru" name="password_confirmation" placeholder="Ulangi kata sandi baru" value={form.data.password_confirmation} onChange={(value) => form.setData('password_confirmation', value)} /><div className="flex justify-end gap-3 pt-4"><Link href="/admin/users" className="px-4 py-2 text-xs text-slate-600">Kembali</Link><button disabled={form.processing} className="rounded-md bg-[#2D4C79] px-5 py-2 text-sm font-medium text-white shadow-sm hover:bg-[#1e3454] disabled:opacity-60">Perbarui Kata Sandi</button></div></form></div></div></AdminLayout>;
}
