import { Head, Link, useForm } from '@inertiajs/react';
import PasswordField from '@/components/password-field';
import AuthPageLayout from '@/layouts/auth-page-layout';

export default function Register() {
    const form = useForm({ nama: '', email: '', password: '', password_confirmation: '' });
    const errors = Object.values(form.errors);
    return <AuthPageLayout variant="register"><Head title="Daftar Akun Pengguna — AduPDF" /><div className="w-full max-w-[448px] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-lg"><div className="bg-[#792D2E] px-6 py-6 text-center text-white"><h1 className="font-serif text-2xl font-bold leading-8">Pendaftaran Pengguna</h1><p className="mt-1 font-serif text-xs leading-4 text-slate-200">Khusus Mahasiswa, Dosen, dan Tenaga Kependidikan</p></div><div className="px-6 pb-6 pt-6"><div className="mb-5 rounded border-l-4 border-[#2D4C79] bg-blue-50 p-3 text-xs leading-[19.5px] text-slate-700"><b className="text-[#2D4C79]">Informasi Akun:</b> Pendaftaran akun langsung aktif. Anda dapat langsung masuk setelah pendaftaran berhasil, lalu lengkapi identitas institusional pada profil untuk melakukan reservasi.</div>{errors.length > 0 && <div role="alert" className="mb-4 rounded border-l-4 border-rose-500 bg-rose-50 p-3 text-sm text-rose-800">{errors.map((error) => <div key={error}>{error}</div>)}</div>}<form onSubmit={(event) => { event.preventDefault(); form.post('/register'); }} className="space-y-4"><div><label htmlFor="nama" className="mb-1 block text-sm font-medium text-slate-700">Nama Lengkap</label><input id="nama" required autoFocus value={form.data.nama} onChange={(event) => form.setData('nama', event.target.value)} placeholder="Contoh: Budi Santoso" className="h-[37.5px] w-full rounded-md border border-slate-300 px-3 text-sm focus:border-[#2D4C79] focus:outline-none focus:ring-2 focus:ring-[#2D4C79]" /></div><div><label htmlFor="email" className="mb-1 block text-sm font-medium text-slate-700">Alamat Email Kampus</label><input id="email" type="email" required value={form.data.email} onChange={(event) => form.setData('email', event.target.value)} placeholder="agil_petugas@adupdf.ac.id" className="h-[37.5px] w-full rounded-md border border-slate-300 px-3 text-sm focus:border-[#2D4C79] focus:outline-none focus:ring-2 focus:ring-[#2D4C79]" /></div><PasswordField label="Kata Sandi" name="password" placeholder="12345678" value={form.data.password} onChange={(value) => form.setData('password', value)} inputClassName="h-[37.5px] py-0" /><PasswordField label="Konfirmasi Kata Sandi" name="password_confirmation" placeholder="Ulangi kata sandi" value={form.data.password_confirmation} onChange={(value) => form.setData('password_confirmation', value)} inputClassName="h-[37.5px] py-0" /><button disabled={form.processing} className="h-10 w-full rounded-lg bg-[#2D4C79] px-4 text-sm font-medium text-white shadow-sm hover:bg-[#1e3454] disabled:opacity-60">Daftar Sekarang</button></form><div className="mt-6 border-t border-slate-200 pt-6 text-center text-xs text-slate-600">Sudah memiliki akun? <Link href="/login" className="ml-1 font-semibold text-[#2D4C79] hover:underline">Masuk di sini</Link></div></div></div></AuthPageLayout>;
}
